{{- if .Values.serviceAccountRoles.advancedClusterRole.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "runwhen-local.serviceAccountName" . }}-advanced-view
rules:
{{ toYaml .Values.serviceAccountRoles.advancedClusterRole.rules | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "runwhen-local.serviceAccountName" . }}-advanced-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "runwhen-local.serviceAccountName" . }}-advanced-view
subjects:
  - kind: ServiceAccount
    name: {{ include "runwhen-local.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}