{{- if .Values.runwhenLocal.enabled -}}
{{- if .Values.runwhenLocal.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runwhenLocal.serviceAccount.name }}
  labels:
    {{- include "runwhen-local.labels" . | nindent 4 }}
  {{- with .Values.runwhenLocal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.runwhenLocal.serviceAccount.name }}-token
  annotations:
    kubernetes.io/service-account.name: {{ .Values.runwhenLocal.serviceAccount.name }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.runwhenLocal.serviceAccount.name }}-sa-secret-manage
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
  resourceNames: ["{{ .Values.runwhenLocal.serviceAccount.name }}-token"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.runwhenLocal.serviceAccount.name }}-a-secret-manage-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.runwhenLocal.serviceAccount.name }}-sa-secret-manage
subjects:
  - kind: ServiceAccount
    name: {{ .Values.runwhenLocal.serviceAccount.name }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}