{{- if .Values.runwhenLocal.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runwhen-local.fullname" . }}
  labels:
    {{- include "runwhen-local.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "runwhen-local.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.runwhenLocal.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "runwhen-local.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.runwhenLocal.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.runwhenLocal.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.runwhenLocal.securityContext | nindent 12 }}
          image: "{{ .Values.runwhenLocal.image.repository }}:{{ .Values.runwhenLocal.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.runwhenLocal.image.pullPolicy }}
          env: 
          - name: AUTORUN_WORKSPACE_BUILDER_INTERVAL
            value: "{{ .Values.runwhenLocal.autoRun.discoveryInterval }}"
          - name: RW_LOCAL_TERMINAL_DISABLED
            value: "{{ .Values.runwhenLocal.terminal.disabled }}"
          - name: RW_LOCAL_UPLOAD_ENABLED
            value: "{{ .Values.runwhenLocal.autoRun.uploadEnabled }}"
          - name: RW_LOCAL_UPLOAD_MERGE_MODE
            value: "{{ .Values.runwhenLocal.autoRun.uploadMergeMode }}"
          {{ if .Values.runwhenLocal.runwhenLocalConfig.debugLogs }}
          - name: DEBUG_LOGGING
            value: "true"
          {{ end }}
          ports:
            - name: mkdocs
              containerPort: 8081
              protocol: TCP
            - name: django
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: mkdocs
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 20
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          resources:
            {{- toYaml .Values.runwhenLocal.resources | nindent 12 }}
          volumeMounts:
          - name: shared-volume
            mountPath: "/shared"
          {{- if .Values.runwhenLocal.discoveryKubeconfig.secretProvided.enabled }}
          - name: secret-volume
            mountPath: "/shared/kubeconfig"
            subPath: "kubeconfig"
          {{- end }}
          - name: configmap-volume
            mountPath: "/shared/workspaceInfo.yaml"
            subPath: "workspaceInfo.yaml"
          {{- with .Values.runwhenLocal.uploadInfo }}
          {{- if . }}
          - name: configmap-volume
            mountPath: "/shared/uploadInfo.yaml"
            subPath: "uploadInfo.yaml"
          {{- end }}
          {{- end }}
      volumes:
      - name: shared-volume
        emptyDir: {}
      {{- if .Values.runwhenLocal.discoveryKubeconfig.secretProvided.enabled }}
      - name: secret-volume
        secret:
          secretName: {{ .Values.runwhenLocal.discoveryKubeconfig.secretProvided.secretName }}
          items:
            - key: {{ .Values.runwhenLocal.discoveryKubeconfig.secretProvided.secretKey }}
              path: {{ .Values.runwhenLocal.discoveryKubeconfig.secretProvided.secretPath }}
      {{- end }}
      - name: configmap-volume
        configMap:
          name: {{ if .Values.runwhenLocal.runwhenLocalConfig.useExistingConfigMap }}{{ .Values.runwhenLocal.runwhenLocalConfig.existingConfigMapName }}{{ else }}{{ .Values.runwhenLocal.runwhenLocalConfig.configMap.name }}{{ end }}

          # items:
          #   - key: workspaceInfo.yaml
          #     path: workspaceInfo.yaml
          #   {{- with .Values.runwhenLocal.uploadInfo }}
          #   {{- if . }}
          #   - key: uploadInfo.yaml
          #     path: uploadInfo.yaml
          #   {{- end }}
          #   {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}