{{- if .Values.runwhenLocal.enabled -}}
{{ if not .Values.runwhenLocal.workspaceInfo.useExistingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.runwhenLocal.workspaceInfo.configMap.name }}
data:
  workspaceInfo.yaml: | 
    workspaceName: {{ .Values.workspaceName }}
    defaultLocation: {{ .Values.runwhenLocal.workspaceInfo.configMap.data.defaultLocation | default "none" }}
    workspaceOwnerEmail: {{ .Values.runwhenLocal.workspaceInfo.configMap.data.workspaceOwnerEmail | default "tester@mycompany.com" }}
    defaultLOD: {{ .Values.runwhenLocal.workspaceInfo.configMap.data.defaultLOD | default "detailed" }}
    namespaces: 
      {{- toYaml .Values.runwhenLocal.workspaceInfo.configMap.data.namespaces | nindent 6 }}
    codeCollections:
      {{- toYaml .Values.runwhenLocal.workspaceInfo.configMap.data.codeCollections | nindent 6 }}
    cloudConfig:
      {{- toYaml .Values.runwhenLocal.workspaceInfo.configMap.data.cloudConfig | nindent 6 }}
    custom:
      {{- toYaml .Values.runwhenLocal.workspaceInfo.configMap.data.custom | nindent 6 }}
{{ end }}
{{ end }}