{{- if .Values.serviceAccountRoles.namespaceRoleView.enabled -}}
{{- range $ns := .Values.serviceAccountRoles.namespaceRoleView.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $ns }}
  name: {{ include "runwhen-local.serviceAccountName" . }}-namespace-view
rules:
- apiGroups: [""] 
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runwhen-local.serviceAccountName" . }}-view-rb
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "runwhen-local.serviceAccountName" . }}-namespace-view
subjects:
  - kind: ServiceAccount
    name: {{ include "runwhen-local.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}