{{- if .Values.runner.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: pushgateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      name: pushgateway
      labels:
        app: pushgateway
        visualize: "true"
        run: pushgateway
      {{- with .Values.runwhenLocal.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway
        command: ["/bin/pushgateway"]
        args: ["--log.level=debug"]
        ports:
        - name: web
          containerPort: 9091
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pushgateway
    visualize: "true"
    app: pushgateway
  name: pushgateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pushgateway
  type: ClusterIP
  ports:
  - name: scrape
    protocol: TCP
    port: 9091
{{- end }}