{{- if .Values.runner.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: otel-collector
  name: otel-collector
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: otel-collector
  name: otel-collector-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: otel-collector-role
subjects:
- kind: ServiceAccount
  name: otel-collector
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: otel-collector
  name: otel-collector-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
# - apiGroups:
#   - ""
#   - discovery.k8s.io
#   - networking.k8s.io
#   resources:
#   - endpoints
#   - endpointslices
#   - pods
#   - services
#   verbs:
#   - get
#   - list
#   - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
{{- end }}
