{{- if .Values.runner.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: pushgateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      name: pushgateway
      labels:
        app: pushgateway
        visualize: "true"
        run: pushgateway
      {{- with .Values.runwhenLocal.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: pushgateway
        image: "{{ (.Values.runner.pushgateway.image.registry | default .Values.registryOverride)| default "docker.io" }}/{{ .Values.runner.pushgateway.image.repository | default "prom/pushgateway" }}:{{ .Values.runner.pushgateway.image.tag | default "latest"}}"
        command: ["/bin/pushgateway"]
        args: ["--log.level=debug"]
        ports:
        - name: web
          containerPort: 9091
        resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (eq .Values.platformArch "arm64") (not (empty .Values.tolerations)) (not (empty .Values.runner.pushgateway.tolerations)) }}
      tolerations:
        {{- if eq .Values.platformArch "arm64" }}
        - key: "kubernetes.io/arch"
          operator: "Equal"
          value: "arm64"
          effect: "NoSchedule"
        {{- end }}
        {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.runner.pushgateway.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pushgateway
    visualize: "true"
    app: pushgateway
  name: pushgateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pushgateway
  type: ClusterIP
  ports:
  - name: scrape
    protocol: TCP
    port: 9091
{{- end }}