{{- if .Values.runner.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: runner
  name: runner
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: runner
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - image: {{ .Values.runner.image | default "us-docker.pkg.dev/runwhen-nonprod-shared/public-images/runner:stable" }}
        imagePullPolicy: {{ .Values.runner.imagePullPolicy | default "IfNotPresent" }}
        name: runner
        ports:
        - containerPort: 9090
          name: metrics
          protocol: TCP
        resources:
          {{- if eq .Values.platformType "EKS_Fargate" }}
          {{- toYaml .Values.runner.resources.EKS_Fargate | nindent 12 }}
          {{- else }}
          {{- toYaml .Values.runner.resources.default | nindent 12 }}
          {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: runner-config-volume
          mountPath: "/etc/runwhen/runner/config.yaml"
          subPath: "config.yaml"
        {{- with .Values.runner.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        - name: RUNNER_CONTROL_ADDR
          value: "{{ .Values.runner.controlAddr | default "https://runner.beta.runwhen.com" }}"
        - name: RUNNER_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        {{- if .Values.proxy.enabled }}
        {{- with .Values.proxy.httpProxy }}
        - name: HTTP_PROXY
          value: {{ . }}
        {{- end }}
        {{- with .Values.proxy.httpsProxy }}
        - name: HTTPS_PROXY
          value: {{ . }}
        {{- end }}
        {{- with .Values.proxy.noProxy }}
        - name: NO_PROXY
          value: {{ . }}
        {{- end }}
        {{- end }}
        {{- with .Values.runner.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.runner.securityContext }}
        securityContext:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: runner
      serviceAccountName: runner
      terminationGracePeriodSeconds: 50
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runner.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: runner-config-volume
        configMap:
          name: {{ .Values.runner.configMap.name }}
      {{ with .Values.runner.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}