{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runwhen-local.serviceAccountName" . }}
  labels:
    {{- include "runwhen-local.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runwhen-local.serviceAccountName" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ include "runwhen-local.serviceAccountName" . }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $ns }}
  name: {{ include "runwhen-local.serviceAccountName" $ }}-sa-secret-self-view
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["{{ include "runwhen-local.serviceAccountName" . }}-token"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runwhen-local.serviceAccountName" $ }}-a-secret-self-view-rb
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "runwhen-local.serviceAccountName" $ }}-sa-secret-self-view
subjects:
  - kind: ServiceAccount
    name: {{ include "runwhen-local.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}