{{- $wb := include "runwhen-local.resolveWorkspaceBuilder" . | fromYaml -}}
{{- if $wb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "runwhen-local.workspaceBuilderFullname" . }}
  labels:
    {{- include "runwhen-local.workspaceBuilderLabels" . | nindent 4 }}
spec:
  type: {{ $wb.service.type }}
  ports:
    - name: api
      protocol: TCP
      port: 8000
      targetPort: api
  selector:
    {{- include "runwhen-local.workspaceBuilderSelectorLabels" . | nindent 4 }}
{{- end }}
