name: Trivy Scan for Critical Vulnerabilities

on:
  workflow_dispatch:
    inputs:
      registries:
        description: "List of image registries to scan"
        required: true
        default: |
          - us-docker.pkg.dev/runwhen-nonprod-shared/public-images/robot-runtime-base-image:latest

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install latest Trivy
        run: |
          TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | jq -r .tag_name)
          wget https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb

      - name: Parse registry list
        id: parse-registries
        run: |
          echo "${{ github.event.inputs.registries }}" | sed 's/- //g' > registries.txt
          echo "Parsed registries:"
          cat registries.txt
      
      - name: Initialize aggregated results
        run: |
          echo '{"Vulnerabilities": []}' > aggregated_results.json

      - name: Scan each registry and aggregate results
        id: trivy-scan
        run: |
          while IFS= read -r registry || [[ -n "$registry" ]]; do
            echo "Scanning $registry..."
            trivy image --severity CRITICAL --ignore-unfixed --scanners vuln --format json "$registry" > trivy_result.json
            cat trivy_result.json
            jq '.Results[].Vulnerabilities' trivy_result.json | jq -c '.[]' | \
            jq -s '{"Vulnerabilities": .}' > vulnerabilities.json
            jq -s '.[0].Vulnerabilities + .[1].Vulnerabilities | {Vulnerabilities: .}' aggregated_results.json vulnerabilities.json > temp.json && mv temp.json aggregated_results.json
          done < registries.txt
          ls 
          cat trivy_result.json

      - name: Calculate aggregated metric
        id: calculate-metrics
        run: |
          critical_count=$(jq '.Vulnerabilities | map(select(.Severity == "CRITICAL")) | length' aggregated_results.json)
          echo "Total Critical vulnerabilities: $critical_count"
          echo "critical_count=$critical_count" >> $GITHUB_ENV

      - name: Upload aggregated results
        uses: actions/upload-artifact@v3
        with:
          name: trivy_aggregated_results
          path: aggregated_results.json

      - name: Display total critical vulnerabilities
        run: |
          echo "Total Critical vulnerabilities: ${{ env.critical_count }}"