name: Trivy Scan for Critical Vulnerabilities

permissions: 
  contents: write

on:
  workflow_dispatch:
    inputs:
      registries:
        description: "List of image registries to scan"
        required: false
        default: |
          - us-docker.pkg.dev/runwhen-nonprod-shared/public-images/robot-runtime-base-image:latest
  schedule:
    - cron: "0 19 * * *"
  pull_request:
    types: [opened, synchronize]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Render Helm Chart to YAML
        id: render-helm
        run: |
          cd charts/runwhen-local
          yq eval '.dependencies[] | .repository' Chart.yaml | while read -r repo; do
            name=$(echo $repo | sed 's|https://||' | sed 's|http://||' | awk -F'/' '{print $1}')
            echo "Adding Helm repository $name with URL $repo"
            helm repo add $name $repo || true
          done
          helm repo update
          helm dependency build
          helm template . --set runner.enabled=true > ../../rendered_chart.yaml
          echo "Rendered Helm chart to YAML in ../../rendered_chart.yaml."

      - name: Verify Rendered YAML File
        run: |
          if [ ! -f "rendered_chart.yaml" ]; then
            echo "Rendered YAML file does not exist!"
            exit 1
          fi
          echo "Rendered YAML file exists."

      - name: Extract Images from Rendered YAML
        id: extract-images
        run: |
          grep -E "image:|\"image:" rendered_chart.yaml \
            | sed -e 's/.*image: *//' -e 's/^"//' -e 's/"$//' > registries.txt
          sort -u registries.txt -o registries.txt
          echo "Images extracted from Helm chart:"
          cat registries.txt
          echo "Total images found: $(wc -l < registries.txt)"

      - name: Add Workflow Input Registries
        id: add-input-registries
        run: |
          # Add additional registries specified in workflow inputs
          echo "${{ github.event.inputs.registries }}" \
            | sed 's/- /\n/g' \
            | sed 's/^ *//;s/ *$//' \
            >> registries.txt
          sort -u registries.txt -o registries.txt
          echo "Combined list of registries:"
          cat registries.txt
          echo "Total registries found: $(wc -l < registries.txt)"

      - name: Install latest Trivy
        run: |
          TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | jq -r .tag_name)
          STRIPPED_VERSION=${TRIVY_VERSION#v}
          wget https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${STRIPPED_VERSION}_Linux-64bit.deb
          sudo dpkg -i trivy_${STRIPPED_VERSION}_Linux-64bit.deb

      - name: Verify registry entries and file reading
        run: |
          echo "Reading registries from registries.txt:"
          while IFS= read -r registry || [[ -n "$registry" ]]; do
            echo "Registry: '$registry'"
          done < registries.txt
    
      - name: Scan each registry and aggregate results
        id: trivy-scan
        run: |
          echo "[]" > aggregated_results.json

          while IFS= read -r registry || [[ -n "$registry" ]]; do
            echo "Scanning registry: '$registry'..."
            if [[ -z "$registry" ]]; then
              echo "Error: Empty registry value detected. Skipping..."
              continue
            fi

            trivy image --severity CRITICAL,HIGH --ignore-unfixed --scanners vuln --format json "$registry" > trivy_result.json
            if [[ ! -s trivy_result.json ]]; then
              echo "Error: Trivy scan failed for '$registry'. Skipping..."
              continue
            fi

            jq --arg registry "$registry" '
              [ .Results[]?
                | (.Vulnerabilities? // [])
                | .[] 
                | . + { "Registry": $registry }
              ]
            ' trivy_result.json > vulnerabilities.json

            jq -s '.[0] + .[1]' aggregated_results.json vulnerabilities.json > temp.json
            mv temp.json aggregated_results.json
          done < registries.txt

      - name: Calculate aggregated metrics
        id: calculate-metrics
        run: |
          echo "Calculating total Critical vulnerabilities..."
          critical_count=$(jq '[ .[] | select(.Severity == "CRITICAL") ] | length' aggregated_results.json)
          echo "Total Critical vulnerabilities: $critical_count"
          echo "critical_count=$critical_count" >> $GITHUB_ENV

          echo "Calculating total High vulnerabilities..."
          high_count=$(jq '[ .[] | select(.Severity == "HIGH") ] | length' aggregated_results.json)
          echo "Total High vulnerabilities: $high_count"
          echo "high_count=$high_count" >> $GITHUB_ENV

      - name: Upload aggregated results
        uses: actions/upload-artifact@v4
        with:
          name: trivy_aggregated_results
          path: aggregated_results.json

      - name: Display total critical vulnerabilities
        run: |
          echo "Total Critical vulnerabilities: ${{ env.critical_count }}"

      - name: Display total high vulnerabilities
        run: |
          echo "Total High vulnerabilities: ${{ env.high_count }}"

      - name: Generate summary output
        id: generate-summary
        run: |
          # Save the summary to a variable
          summary=$(jq -r '
            def group_vulns:
              reduce .[] as $v ({}; 
                # Include PkgName in the key to group on (optional, but recommended)
                .[$v.VulnerabilityID + "@" + $v.PkgName + "@" + $v.InstalledVersion + "@" + $v.FixedVersion]
                  += [ $v ]
              );
            group_vulns
            | to_entries
            | map(.value)
            | flatten
            # Use unique_by all four fields if you want them de-duplicated strictly
            | unique_by(.VulnerabilityID, .PkgName, .InstalledVersion, .FixedVersion)
            | sort_by(.Registry)
            | (["Registry","Package","Vulnerability ID","Installed Version","Fixed Version","Severity"]
              | (., map(length * "-"))),
              (.[]
                | [.Registry, .PkgName, .VulnerabilityID, .InstalledVersion, .FixedVersion, .Severity])
            | @tsv
          ' aggregated_results.json | column -t -s $'\t')


          # Write the summary as an output so we can access it in subsequent steps
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$summary" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # -------------------------------------------
      # Step to insert/overwrite summary in README
      # -------------------------------------------
      - name: Update README with Trivy Summary
        run: |
          # 1) Grab the summary string from the previous step
          summary="$(echo '```'; echo "${{ steps.generate-summary.outputs.summary }}"; echo '```')"

          # 2) Define start and end markers
          start_marker="<!-- START_TRIVY_SUMMARY -->"
          end_marker="<!-- END_TRIVY_SUMMARY -->"

          # 3) If the markers do NOT exist, append them at the end of README
          if ! grep -q "$start_marker" README.md; then
            echo "" >> README.md
            echo "$start_marker" >> README.md
            echo "$end_marker" >> README.md
          else
            # If they do exist, remove everything in between, leaving the markers
            sed -i "/$start_marker/,/$end_marker/{/$start_marker/!{/$end_marker/!d}}" README.md
          fi

          # 4) Insert the new summary between those markers
          #    `sed -i "/$start_marker/ r /dev/stdin" README.md <<< "$summary"`
          #    reads summary from stdin and inserts it after the line with $start_marker.
          sed -i "/$start_marker/ r /dev/stdin" README.md <<< "$summary"

      - name: Commit changes (README only)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage the README if it changed:
          git add README.md

          # Check if there is something to commit
          if git diff --cached --exit-code; then
            echo "No changes detected in README.md. Skipping commit."
            exit 0
          else
            git commit -m "chore: update README with Trivy summary"
            git push
          fi